import {
  AppendixHslLightnessFormulaSlide,
  AppendixLchPolarCoordinatesSlide,
  AppendixOklchChromaLimitSlide,
  AppendixOklchChromaStrategiesSlide,
  AppendixOklchColorChecklistSlide,
  AppendixOklchContrastCheckSlide,
  AppendixOklchHclRolesSlide,
  AppendixOklchStartWithLightnessSlide,
  AppendixPerceptualUniformitySlide,
  AppendixPresentationScopeSlide,
  AppendixRgbGamutFamilySlide,
  AppendixTerminologyMapSlide,
} from "@/presentation/PresentationAppendixSlides"
import {
  GamutConceptSlide,
  PerceptualGamutShapeSlide,
  RgbGamutCubeSlide,
} from "@/presentation/PresentationPerceptualSlides"

export const PRESENTATION_APPENDIX_SLIDE_IDS = [
  "appendix-presentation-scope",
  "appendix-terminology-map",
  "appendix-rgb-gamut-family",
  "appendix-hsl-lightness-formula",
  "appendix-perceptual-uniformity",
  "appendix-lch-polar-coordinates",
  "appendix-gamut-concept",
  "appendix-rgb-gamut-cube",
  "appendix-perceptual-gamut-shape",
  "appendix-oklch-chroma-limit",
  "appendix-oklch-contrast-check",
  "appendix-oklch-start-with-lightness",
  "appendix-oklch-hcl-roles",
  "appendix-oklch-chroma-strategies",
  "appendix-oklch-color-checklist",
] as const

export type PresentationAppendixSlideId =
  (typeof PRESENTATION_APPENDIX_SLIDE_IDS)[number]

export const PRESENTATION_APPENDIX_SLIDES = [
  {
    appendixFor: "agenda",
    component: AppendixPresentationScopeSlide,
    id: "appendix-presentation-scope",
    kind: "appendix",
    selectLabel: "A1 발표 범위",
    title: "발표 범위",
  },
  {
    appendixFor: "color-models",
    component: AppendixTerminologyMapSlide,
    id: "appendix-terminology-map",
    kind: "appendix",
    selectLabel: "B1 용어 정리",
    title: "용어 정리",
  },
  {
    appendixFor: "rgb-strengths",
    component: AppendixRgbGamutFamilySlide,
    id: "appendix-rgb-gamut-family",
    kind: "appendix",
    selectLabel: "C1 RGB 계열",
    title: "RGB 계열",
  },
  {
    appendixFor: "hsl-lightness-trap",
    component: AppendixHslLightnessFormulaSlide,
    id: "appendix-hsl-lightness-formula",
    kind: "appendix",
    selectLabel: "D1 HSL Lightness",
    title: "HSL 공식",
  },
  {
    appendixFor: "perceptual-models",
    component: AppendixPerceptualUniformitySlide,
    id: "appendix-perceptual-uniformity",
    kind: "appendix",
    selectLabel: "E1 지각 균일성",
    title: "지각 균일성",
  },
  {
    appendixFor: "lch-model",
    component: AppendixLchPolarCoordinatesSlide,
    id: "appendix-lch-polar-coordinates",
    kind: "appendix",
    selectLabel: "F2 LCH 극좌표",
    title: "Lab/LCH 심화",
  },
  {
    appendixFor: "out-of-gamut",
    component: GamutConceptSlide,
    id: "appendix-gamut-concept",
    kind: "appendix",
    selectLabel: "G1 색역",
    title: "색역",
  },
  {
    appendixFor: "out-of-gamut",
    component: RgbGamutCubeSlide,
    id: "appendix-rgb-gamut-cube",
    kind: "appendix",
    selectLabel: "G2 sRGB 삼각형",
    title: "sRGB는 xy에서 삼각형이다",
  },
  {
    appendixFor: "out-of-gamut",
    component: PerceptualGamutShapeSlide,
    id: "appendix-perceptual-gamut-shape",
    kind: "appendix",
    selectLabel: "G3 Lab 색역 단면",
    title: "Lab 단면에서는 경계가 휘어진다",
  },
  {
    appendixFor: "oklch-model",
    component: AppendixOklchChromaLimitSlide,
    id: "appendix-oklch-chroma-limit",
    kind: "appendix",
    selectLabel: "H1 Chroma 한계",
    title: "OKLCH caveat",
  },
  {
    appendixFor: "oklch-lightness",
    component: AppendixOklchContrastCheckSlide,
    id: "appendix-oklch-contrast-check",
    kind: "appendix",
    selectLabel: "H3 대비 검증",
    title: "OKLCH와 접근성",
  },
  {
    appendixFor: "oklch-brand-palette",
    component: AppendixOklchStartWithLightnessSlide,
    id: "appendix-oklch-start-with-lightness",
    kind: "appendix",
    selectLabel: "I1 L부터 정하기",
    title: "OKLCH 색 정하기",
  },
  {
    appendixFor: "oklch-brand-palette",
    component: AppendixOklchHclRolesSlide,
    id: "appendix-oklch-hcl-roles",
    kind: "appendix",
    selectLabel: "I2 H/C/L 역할",
    title: "OKLCH 색 정하기",
  },
  {
    appendixFor: "oklch-brand-palette",
    component: AppendixOklchChromaStrategiesSlide,
    id: "appendix-oklch-chroma-strategies",
    kind: "appendix",
    selectLabel: "I3 C 전략",
    title: "OKLCH 색 정하기",
  },
  {
    appendixFor: "choose-the-tool",
    component: AppendixOklchColorChecklistSlide,
    id: "appendix-oklch-color-checklist",
    kind: "appendix",
    selectLabel: "I4 체크리스트",
    title: "OKLCH 색 정하기",
  },
] as const
