import {
  AgendaPresentationSlide,
  ColorModelIntroPresentationSlide,
  IntroPresentationSlide,
  RgbIntroPresentationSlide,
} from "@/presentation/PresentationSlides"
import {
  AxisPalettesSlide,
  HslHsvIntroPresentationSlide,
  HslLightnessTrapSlide,
  HslModelSlide,
  HslVsHsvSlide,
  HsvModelSlide,
  HsvPickerSlide,
  RgbDerivedLimitsSlide,
} from "@/presentation/PresentationHslHsvSlides"
import { HslOklchSolidComparisonSlide } from "@/presentation/PresentationHslOklchSolidComparisonSlide"
import {
  LabModelSlide,
  LabToOklabSlide,
  LchModelSlide,
  OklchModelSlide,
  OutOfGamutSlide,
  Part1SummarySlide,
  PerceptualModelsSlide,
} from "@/presentation/PresentationPerceptualSlides"
import {
  ChooseTheToolSlide,
  OklchBrandPaletteSlide,
  OklchDarkModeSlide,
  OklchGradientSlide,
  OklchLightnessSlide,
  OklchStateColorsSlide,
  Part2IntroSlide,
  WhyOklchSlide,
} from "@/presentation/PresentationOklchPracticeSlides"
import {
  RgbLimitsSlide,
  RgbModelSlide,
  RgbStrengthsSlide,
} from "@/presentation/PresentationRgbModelSlide"

export const PRESENTATION_MAIN_SLIDE_IDS = [
  "intro",
  "agenda",
  "color-models",
  "rgb-intro",
  "rgb-model",
  "rgb-strengths",
  "rgb-limits",
  "hsl-hsv-intro",
  "hsl-model",
  "hsv-model",
  "hsv-picker",
  "hsl-vs-hsv",
  "axis-palettes",
  "hsl-lightness-trap",
  "rgb-derived-limits",
  "perceptual-models",
  "lab-model",
  "lch-model",
  "lab-to-oklab",
  "oklch-model",
  "out-of-gamut",
  "hsl-oklch-solid-comparison",
  "part-1-summary",
  "part-2-intro",
  "why-oklch",
  "oklch-lightness",
  "oklch-brand-palette",
  "oklch-state-colors",
  "oklch-gradient",
  "oklch-dark-mode",
  "choose-the-tool",
] as const

export type PresentationMainSlideId = (typeof PRESENTATION_MAIN_SLIDE_IDS)[number]

export const PRESENTATION_MAIN_SLIDES = [
  {
    component: IntroPresentationSlide,
    id: "intro",
    kind: "main",
    title: "RGB부터 OKLCH까지",
  },
  { component: AgendaPresentationSlide, id: "agenda", kind: "main", title: "오늘의 지도" },
  {
    component: ColorModelIntroPresentationSlide,
    id: "color-models",
    kind: "main",
    title: "색 모델",
  },
  { component: RgbIntroPresentationSlide, id: "rgb-intro", kind: "main", title: "RGB" },
  {
    component: RgbModelSlide,
    id: "rgb-model",
    kind: "main",
    title: "RGB: 기계가 좋아하는 색 모델",
  },
  { component: RgbStrengthsSlide, id: "rgb-strengths", kind: "main", title: "RGB의 장점" },
  { component: RgbLimitsSlide, id: "rgb-limits", kind: "main", title: "RGB의 한계" },
  { component: HslHsvIntroPresentationSlide, id: "hsl-hsv-intro", kind: "main", title: "HSL과 HSV" },
  { component: HslModelSlide, id: "hsl-model", kind: "main", title: "HSL" },
  { component: HsvModelSlide, id: "hsv-model", kind: "main", title: "HSV" },
  { component: HsvPickerSlide, id: "hsv-picker", kind: "main", title: "HSV Color Picker" },
  { component: HslVsHsvSlide, id: "hsl-vs-hsv", kind: "main", title: "HSL vs HSV" },
  { component: AxisPalettesSlide, id: "axis-palettes", kind: "main", title: "왜 편리한가" },
  { component: HslLightnessTrapSlide, id: "hsl-lightness-trap", kind: "main", title: "HSL의 함정" },
  { component: RgbDerivedLimitsSlide, id: "rgb-derived-limits", kind: "main", title: "RGB 기반 색 모델의 한계" },
  { component: PerceptualModelsSlide, id: "perceptual-models", kind: "main", title: "지각 기반 색 모델의 대두" },
  { component: LabModelSlide, id: "lab-model", kind: "main", title: "Lab" },
  { component: LchModelSlide, id: "lch-model", kind: "main", title: "LCH" },
  { component: LabToOklabSlide, id: "lab-to-oklab", kind: "main", title: "Lab에서 Oklab으로" },
  { component: OklchModelSlide, id: "oklch-model", kind: "main", title: "OKLCH" },
  { component: OutOfGamutSlide, id: "out-of-gamut", kind: "main", title: "Out of gamut" },
  { component: HslOklchSolidComparisonSlide, id: "hsl-oklch-solid-comparison", kind: "main", title: "HSL vs OKLCH" },
  { component: Part1SummarySlide, id: "part-1-summary", kind: "main", title: "1부 정리" },
  { component: Part2IntroSlide, id: "part-2-intro", kind: "main", title: "2부" },
  { component: WhyOklchSlide, id: "why-oklch", kind: "main", title: "HSL으로는 부족한 이유" },
  { component: OklchLightnessSlide, id: "oklch-lightness", kind: "main", title: "OKLCH는 명도 설계가 쉽다" },
  { component: OklchBrandPaletteSlide, id: "oklch-brand-palette", kind: "main", title: "브랜드 팔레트를 규칙으로 만들기" },
  { component: OklchStateColorsSlide, id: "oklch-state-colors", kind: "main", title: "상태 색상을 관계로 만들기" },
  { component: OklchGradientSlide, id: "oklch-gradient", kind: "main", title: "자연스러운 그라데이션" },
  { component: OklchDarkModeSlide, id: "oklch-dark-mode", kind: "main", title: "다크모드 설계" },
  { component: ChooseTheToolSlide, id: "choose-the-tool", kind: "main", title: "도구 선택" },
] as const
