/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from "./routes/__root"
import { Route as SrgbP3CompareRouteImport } from "./routes/srgb-p3-compare"
import { Route as CssColorNotationsRouteImport } from "./routes/css-color-notations"
import { Route as ColorSpaceUnwrappedRouteImport } from "./routes/color-space-unwrapped"
import { Route as ColorSpaceSolidModelsRouteImport } from "./routes/color-space-solid-models"
import { Route as ColorInterpolationRouteImport } from "./routes/color-interpolation"
import { Route as ColorGamutClippingRouteImport } from "./routes/color-gamut-clipping"
import { Route as ColorCoordinatePlanesRouteImport } from "./routes/color-coordinate-planes"
import { Route as ArduinoRgbRouteImport } from "./routes/arduino-rgb"
import { Route as IndexRouteImport } from "./routes/index"

const SrgbP3CompareRoute = SrgbP3CompareRouteImport.update({
  id: "/srgb-p3-compare",
  path: "/srgb-p3-compare",
  getParentRoute: () => rootRouteImport,
} as any)
const CssColorNotationsRoute = CssColorNotationsRouteImport.update({
  id: "/css-color-notations",
  path: "/css-color-notations",
  getParentRoute: () => rootRouteImport,
} as any)
const ColorSpaceUnwrappedRoute = ColorSpaceUnwrappedRouteImport.update({
  id: "/color-space-unwrapped",
  path: "/color-space-unwrapped",
  getParentRoute: () => rootRouteImport,
} as any)
const ColorSpaceSolidModelsRoute = ColorSpaceSolidModelsRouteImport.update({
  id: "/color-space-solid-models",
  path: "/color-space-solid-models",
  getParentRoute: () => rootRouteImport,
} as any)
const ColorInterpolationRoute = ColorInterpolationRouteImport.update({
  id: "/color-interpolation",
  path: "/color-interpolation",
  getParentRoute: () => rootRouteImport,
} as any)
const ColorGamutClippingRoute = ColorGamutClippingRouteImport.update({
  id: "/color-gamut-clipping",
  path: "/color-gamut-clipping",
  getParentRoute: () => rootRouteImport,
} as any)
const ColorCoordinatePlanesRoute = ColorCoordinatePlanesRouteImport.update({
  id: "/color-coordinate-planes",
  path: "/color-coordinate-planes",
  getParentRoute: () => rootRouteImport,
} as any)
const ArduinoRgbRoute = ArduinoRgbRouteImport.update({
  id: "/arduino-rgb",
  path: "/arduino-rgb",
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: "/",
  path: "/",
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  "/": typeof IndexRoute
  "/arduino-rgb": typeof ArduinoRgbRoute
  "/color-coordinate-planes": typeof ColorCoordinatePlanesRoute
  "/color-gamut-clipping": typeof ColorGamutClippingRoute
  "/color-interpolation": typeof ColorInterpolationRoute
  "/color-space-solid-models": typeof ColorSpaceSolidModelsRoute
  "/color-space-unwrapped": typeof ColorSpaceUnwrappedRoute
  "/css-color-notations": typeof CssColorNotationsRoute
  "/srgb-p3-compare": typeof SrgbP3CompareRoute
}
export interface FileRoutesByTo {
  "/": typeof IndexRoute
  "/arduino-rgb": typeof ArduinoRgbRoute
  "/color-coordinate-planes": typeof ColorCoordinatePlanesRoute
  "/color-gamut-clipping": typeof ColorGamutClippingRoute
  "/color-interpolation": typeof ColorInterpolationRoute
  "/color-space-solid-models": typeof ColorSpaceSolidModelsRoute
  "/color-space-unwrapped": typeof ColorSpaceUnwrappedRoute
  "/css-color-notations": typeof CssColorNotationsRoute
  "/srgb-p3-compare": typeof SrgbP3CompareRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  "/": typeof IndexRoute
  "/arduino-rgb": typeof ArduinoRgbRoute
  "/color-coordinate-planes": typeof ColorCoordinatePlanesRoute
  "/color-gamut-clipping": typeof ColorGamutClippingRoute
  "/color-interpolation": typeof ColorInterpolationRoute
  "/color-space-solid-models": typeof ColorSpaceSolidModelsRoute
  "/color-space-unwrapped": typeof ColorSpaceUnwrappedRoute
  "/css-color-notations": typeof CssColorNotationsRoute
  "/srgb-p3-compare": typeof SrgbP3CompareRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | "/"
    | "/arduino-rgb"
    | "/color-coordinate-planes"
    | "/color-gamut-clipping"
    | "/color-interpolation"
    | "/color-space-solid-models"
    | "/color-space-unwrapped"
    | "/css-color-notations"
    | "/srgb-p3-compare"
  fileRoutesByTo: FileRoutesByTo
  to:
    | "/"
    | "/arduino-rgb"
    | "/color-coordinate-planes"
    | "/color-gamut-clipping"
    | "/color-interpolation"
    | "/color-space-solid-models"
    | "/color-space-unwrapped"
    | "/css-color-notations"
    | "/srgb-p3-compare"
  id:
    | "__root__"
    | "/"
    | "/arduino-rgb"
    | "/color-coordinate-planes"
    | "/color-gamut-clipping"
    | "/color-interpolation"
    | "/color-space-solid-models"
    | "/color-space-unwrapped"
    | "/css-color-notations"
    | "/srgb-p3-compare"
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ArduinoRgbRoute: typeof ArduinoRgbRoute
  ColorCoordinatePlanesRoute: typeof ColorCoordinatePlanesRoute
  ColorGamutClippingRoute: typeof ColorGamutClippingRoute
  ColorInterpolationRoute: typeof ColorInterpolationRoute
  ColorSpaceSolidModelsRoute: typeof ColorSpaceSolidModelsRoute
  ColorSpaceUnwrappedRoute: typeof ColorSpaceUnwrappedRoute
  CssColorNotationsRoute: typeof CssColorNotationsRoute
  SrgbP3CompareRoute: typeof SrgbP3CompareRoute
}

declare module "@tanstack/react-router" {
  interface FileRoutesByPath {
    "/srgb-p3-compare": {
      id: "/srgb-p3-compare"
      path: "/srgb-p3-compare"
      fullPath: "/srgb-p3-compare"
      preLoaderRoute: typeof SrgbP3CompareRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/css-color-notations": {
      id: "/css-color-notations"
      path: "/css-color-notations"
      fullPath: "/css-color-notations"
      preLoaderRoute: typeof CssColorNotationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/color-space-unwrapped": {
      id: "/color-space-unwrapped"
      path: "/color-space-unwrapped"
      fullPath: "/color-space-unwrapped"
      preLoaderRoute: typeof ColorSpaceUnwrappedRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/color-space-solid-models": {
      id: "/color-space-solid-models"
      path: "/color-space-solid-models"
      fullPath: "/color-space-solid-models"
      preLoaderRoute: typeof ColorSpaceSolidModelsRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/color-interpolation": {
      id: "/color-interpolation"
      path: "/color-interpolation"
      fullPath: "/color-interpolation"
      preLoaderRoute: typeof ColorInterpolationRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/color-gamut-clipping": {
      id: "/color-gamut-clipping"
      path: "/color-gamut-clipping"
      fullPath: "/color-gamut-clipping"
      preLoaderRoute: typeof ColorGamutClippingRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/color-coordinate-planes": {
      id: "/color-coordinate-planes"
      path: "/color-coordinate-planes"
      fullPath: "/color-coordinate-planes"
      preLoaderRoute: typeof ColorCoordinatePlanesRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/arduino-rgb": {
      id: "/arduino-rgb"
      path: "/arduino-rgb"
      fullPath: "/arduino-rgb"
      preLoaderRoute: typeof ArduinoRgbRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/": {
      id: "/"
      path: "/"
      fullPath: "/"
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ArduinoRgbRoute: ArduinoRgbRoute,
  ColorCoordinatePlanesRoute: ColorCoordinatePlanesRoute,
  ColorGamutClippingRoute: ColorGamutClippingRoute,
  ColorInterpolationRoute: ColorInterpolationRoute,
  ColorSpaceSolidModelsRoute: ColorSpaceSolidModelsRoute,
  ColorSpaceUnwrappedRoute: ColorSpaceUnwrappedRoute,
  CssColorNotationsRoute: CssColorNotationsRoute,
  SrgbP3CompareRoute: SrgbP3CompareRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
